version: '3'
#TODO add secrets for db config
#TODO volumes for logs
services:

  postgres:
    image: "postgres:11"
    container_name: postgres
    environment:
        POSTGRES_PASSWORD: <your_password>
        POSTGRES_USER: <your_name>
        POSTGRES_DB: drs_db
    volumes:
        - "db-data:/var/lib/postgresql/data" # database itself
    ports:
        - "5432:5432"

  pg_admin:
    image: "adminer"
    container_name: adminer
    ports:
        - "8082:8080"

  webapp:
    build:
      context: ./
      dockerfile: Dockerfile-webapp
    links:
      - "postgres"
      - "pg_admin"
    image: webapp
    command:
      - "java"
      - "-jar"
      - "data-repository-service-0.0.1-SNAPSHOT.jar"

    ports:
      - "8081:8080"


volumes:
  db-data: